<!-- Theme Stylesheets -->
<link rel="stylesheet" type="text/css" href="themes/${theme}/css/theme.css" />

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="js/lib/html5shiv.js"></script>
  <script src="js/lib/respond.min.js"></script>
<![endif]-->

<!-- Scripts -->
<script type="text/javascript" src="js/lib/javascript.builtins.js"></script>
<script type="text/javascript" src="js/lib/jquery-1.7.js"></script>
<script type="text/javascript" src="js/lib/jquery.color.js"></script>
<script type="text/javascript" src="js/lib/jquery.cookie.js"></script>
<script type="text/javascript" src="js/lib/jquery.urlParams.js"></script>
<script type="text/javascript" src="js/lib/jquery.scrollintoview.js"></script>
<script type="text/javascript" src="js/lib/moment.js"></script>
<script type="text/javascript" src="js/lib/bootstrap.js"></script>

<script type="text/javascript" src="js/catdv/RestApi.js"></script>
<script type="text/javascript" src="js/catdv/Util.js"></script>

<script type="text/javascript" src="js/controls/DragManager.js"></script>
<script type="text/javascript" src="js/controls/StandardControls.js"></script>
<script type="text/javascript" src="js/controls/DataSource.js"></script>
<script type="text/javascript" src="js/controls/DataTable.js"></script>
<script type="text/javascript" src="js/controls/Bootstrap.js"></script>
<script type="text/javascript" src="js/controls/TreeView.js"></script>
<script type="text/javascript" src="js/controls/VideoPlayer.js"></script>
<script type="text/javascript" src="js/controls/SequencePlayer.js"></script>

<script type="text/javascript" src="js/logic/FieldAccessors.js"></script>
<script type="text/javascript" src="js/logic/BuiltInFields.js"></script>
<script type="text/javascript" src="js/logic/ClipManager.js"></script>
<script type="text/javascript" src="js/logic/ServerSettings.js"></script>
<script type="text/javascript" src="js/logic/DetailPanels.js"></script>
<script type="text/javascript" src="js/logic/ViewColumns.js"></script>

<script type="text/javascript" src="js/ui/panels/NavbarLoginMenu.js"></script>

