module logic
{
    import FieldDefinition = catdv.FieldDefinition;

    export var SpecialQueryFields: FieldDefinition[] = [
        {
            "ID": "TEXT",
            "memberOf": "clip",
            "identifier": "text",
            "name": "Name/Notes",
            "description": "Clip name or notes fields",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true
        },
        {
            "ID": "LOGTEXT",
            "memberOf": "clip",
            "identifier": "logtext",
            "name": "Any Logging Field",
            "description": "Any user-defined clip field",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true
        },
        {
            "ID": "ANYTEXT",
            "memberOf": "clip",
            "identifier": "anytext",
            "name": "Any Logging Field",
            "description": "Any user-defined or metedata field",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true
        }
    ];

    export var BuiltInFields: { [ID: string]: FieldDefinition } = {
        "MK": {
            "ID": "MK",
            "memberOf": "clip",
            "identifier": "marked",
            "name": "Mark",
            "description": "Is the clip marked?",
            "fieldType": "checkbox",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "HID": {
            "ID": "HID",
            "memberOf": "clip",
            "identifier": "hidden",
            "name": "Hide",
            "description": "Is the clip normally hidden from view?",
            "fieldType": "checkbox",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "BN": {
            "ID": "BN",
            "memberOf": "clip",
            "identifier": "bin",
            "name": "Bin",
            "description": "Bin or folder name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "TP": {
            "ID": "TP",
            "memberOf": "clip",
            "identifier": "tape",
            "name": "Tape",
            "description": "Tape or reel name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "NM1": {
            "ID": "NM1",
            "memberOf": "clip",
            "identifier": "name",
            "name": "Name",
            "description": "Clip name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "isSortable": true
        },
        "NM2": {
            "ID": "NM2",
            "memberOf": "clip",
            "identifier": "description",
            "name": "Name (Long)",
            "description": "Long clip name, including tape or bin prefix",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "I1": {
            "ID": "I1",
            "memberOf": "clip",
            "identifier": "in",
            "name": "In",
            "description": "Timecode value at start of clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "O1": {
            "ID": "O1",
            "memberOf": "clip",
            "identifier": "out",
            "name": "Out",
            "description": "Timecode value at end of clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "D1": {
            "ID": "D1",
            "memberOf": "clip",
            "identifier": "duration",
            "name": "Duration",
            "description": "Length of clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "IO": {
            "ID": "IO",
            "memberOf": "clip",
            "identifier": "inOut",
            "name": "In & Out",
            "description": "Clip In & Out points",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "I2": {
            "ID": "I2",
            "memberOf": "clip",
            "identifier": "in2",
            "name": "In 2",
            "description": "Start of selection within clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "O2": {
            "ID": "O2",
            "memberOf": "clip",
            "identifier": "out2",
            "name": "Out 2",
            "description": "End of selection within clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "IO2": {
            "ID": "IO2",
            "memberOf": "clip",
            "identifier": "selection",
            "name": "Selection",
            "description": "Clip selection (In2 & Out2)",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "D2": {
            "ID": "D2",
            "memberOf": "clip",
            "identifier": "duration2",
            "name": "Duration 2",
            "description": "Duration of selection within clip",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 100,
            "isSortable": true
        },
        "SS": {
            "ID": "SS",
            "memberOf": "clip",
            "identifier": "start",
            "name": "Clip Start",
            "description": "Start of clip or selection, depending on export preference",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "EE": {
            "ID": "EE",
            "memberOf": "clip",
            "identifier": "end",
            "name": "Clip End",
            "description": "End of clip or selection, depending on export preference",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "EM1": {
            "ID": "EM1",
            "memberOf": "clip",
            "identifier": "outInclusive",
            "name": "Out (incl)",
            "description": "End of clip or selection using inclusive timecode numbering, ie. minus one frame",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "LL": {
            "ID": "LL",
            "memberOf": "clip",
            "identifier": "length",
            "name": "Clip Length",
            "description": "Length of clip or selection, depending on export preference",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MTI": {
            "ID": "MTI",
            "memberOf": "media",
            "identifier": "start",
            "name": "Media Start",
            "description": "Start timecode of the source media file",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MTO": {
            "ID": "MTO",
            "memberOf": "media",
            "identifier": "end",
            "name": "Media Duration",
            "description": "Duration of the source media file",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "GD": {
            "ID": "GD",
            "memberOf": "clip",
            "identifier": "good",
            "name": "Good",
            "description": "Status (good/no good/maybe)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "RTG": {
            "ID": "RTG",
            "memberOf": "clip",
            "identifier": "rating",
            "name": "Rating",
            "description": "Star rating (1=no good, 5=excellent)",
            "fieldType": "number",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "RTGTYP": {
            "ID": "RTGTYP",
            "memberOf": "clip",
            "identifier": "ratingTypeGPS",
            "name": "Rating",
            "description": "Combined rating, type icon & geotag information",
            "fieldType": "compound",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TYPGPS": {
            "ID": "TYPGPS",
            "memberOf": "clip",
            "identifier": "typeGPS",
            "name": "Type",
            "description": "Combined clip type icon & geotag information",
            "fieldType": "compound",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MKHID": {
            "ID": "MKHID",
            "memberOf": "clip",
            "identifier": "markedHidden",
            "name": "Mark",
            "description": "Combined marked & hidden checkboxes",
            "fieldType": "compound",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "STS": {
            "ID": "STS",
            "memberOf": "clip",
            "identifier": "status",
            "name": "Status",
            "description": "Clip status",
            "fieldType": "picklist",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "NT": {
            "ID": "NT",
            "memberOf": "clip",
            "identifier": "notes",
            "name": "Notes",
            "description": "Description or comments on the clip",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "BIG": {
            "ID": "BIG",
            "memberOf": "clip",
            "identifier": "bigNotes",
            "name": "Big Notes",
            "description": "Additional comments (not limited to 64K on server)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "IS2": {
            "ID": "IS2",
            "memberOf": "importSource",
            "identifier": "file",
            "name": "Import Source Path",
            "description": "Input source file (complete path)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "SD1": {
            "ID": "SD1",
            "memberOf": "importSource",
            "identifier": "modifiedDate",
            "name": "Source Date",
            "description": "Modification date of input source file (date only)",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "SD2": {
            "ID": "SD2",
            "memberOf": "importSource",
            "identifier": "modifiedDateTime",
            "name": "Source Date",
            "description": "Modification date & time of input source file",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "DT0": {
            "ID": "DT0",
            "memberOf": "clip",
            "identifier": "firstDate",
            "name": "Date",
            "description": "Source date (record date or timestamp of source file) - date only",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "DT1": {
            "ID": "DT1",
            "memberOf": "clip",
            "identifier": "firstDate",
            "name": "Date/Time",
            "description": "Source date (record date or timestamp of source file) - date & time",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "DT2": {
            "ID": "DT2",
            "memberOf": "clip",
            "identifier": "firstDate",
            "name": "Month",
            "description": "Source date (record date or timestamp of source file) - month & year only",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TY1": {
            "ID": "TY1",
            "memberOf": "clip",
            "identifier": "underlyingType",
            "name": "Underlying Type",
            "description": "Old clip type (including DV start/end of scene indication)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TY2": {
            "ID": "TY2",
            "memberOf": "clip",
            "identifier": "type",
            "name": "Type",
            "description": "New clip type icon (including master/subclip & offline indication)",
            "fieldType": "typeicon",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 45,
            "isSortable": true
        },
        "TY3": {
            "ID": "TY3",
            "memberOf": "clip",
            "identifier": "type",
            "name": "Type",
            "description": "Old clip type icon (including DV start/end of scene indication)",
            "fieldType": "typeicon",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "isSortable": true
        },
        "TY4": {
            "ID": "TY4",
            "memberOf": "clip",
            "identifier": "type",
            "name": "Type",
            "description": "New clip type (including master/subclip & offline indication)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "P1": {
            "ID": "P1",
            "memberOf": "clip",
            "identifier": "posterID",
            "name": "Poster",
            "description": "Default thumbnail for clip",
            "fieldType": "thumbnail",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "width": 68
        },
        "P2": {
            "ID": "P2",
            "memberOf": "clip",
            "identifier": "posterFrame",
            "name": "Poster Frame",
            "description": "Timecode value of poster frame",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "P3": {
            "ID": "P3",
            "memberOf": "clip",
            "identifier": "posterID",
            "name": "Poster (Small)",
            "description": "Tiny version of poster icon",
            "fieldType": "thumbnail",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "ID1": {
            "ID": "ID1",
            "memberOf": "importSource",
            "identifier": "importedDate",
            "name": "Import Date",
            "description": "Date clip was imported into catalog",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "ID2": {
            "ID": "ID2",
            "memberOf": "importSource",
            "identifier": "importedDate",
            "name": "Import Date",
            "description": "Date & time clip was imported into catalog",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "XP": {
            "ID": "XP",
            "memberOf": "clip",
            "identifier": "dvinfo.exposure",
            "name": "Exposure",
            "description": "DV or Exif camera exposure details",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "RD1": {
            "ID": "RD1",
            "memberOf": "clip",
            "identifier": "recordedDate",
            "name": "Record Date",
            "description": "Date & time of creation or shooting (eg. from DV or Exif data)",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "isSortable": true
        },
        "DBG": {
            "ID": "DBG",
            "memberOf": "clip",
            "identifier": "dvinfo",
            "name": "DV Debug",
            "description": "Debug only",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TTI": {
            "ID": "TTI",
            "memberOf": "importSource",
            "identifier": "timeToImport",
            "name": "Time To Import",
            "description": "Time taken to analyse file",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "DT": {
            "ID": "DT",
            "memberOf": "clip",
            "identifier": "dvinfo.timecode",
            "name": "DV T/C",
            "description": "DV timecode value",
            "fieldType": "timecode",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MD1": {
            "ID": "MD1",
            "memberOf": "clip",
            "identifier": "modifiedDate",
            "name": "Modified",
            "description": "Date clip created or last modified by user",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false,
            "isSortable": true
        },
        "VF": {
            "ID": "VF",
            "memberOf": "media",
            "identifier": "videoFormat",
            "name": "Video",
            "description": "Video format",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "AF": {
            "ID": "AF",
            "memberOf": "media",
            "identifier": "audioFormat",
            "name": "Audio",
            "description": "Audio format",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "MI": {
            "ID": "MI",
            "memberOf": "media",
            "identifier": "importer",
            "name": "Importer",
            "description": "Movie importer",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "AR": {
            "ID": "AR",
            "memberOf": "media",
            "identifier": "audioRate",
            "name": "Audio Rate",
            "description": "Audio sample rate",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "ACHN": {
            "ID": "ACHN",
            "memberOf": "media",
            "identifier": "audioChannels",
            "name": "Audio Channels",
            "description": "Number of audio tracks or channels",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "ABIT": {
            "ID": "ABIT",
            "memberOf": "media",
            "identifier": "audioBits",
            "name": "Audio Bits",
            "description": "Audio bit depth",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "QT": {
            "ID": "QT",
            "memberOf": "media",
            "identifier": "qtTracks",
            "name": "QT Tracks",
            "description": "Identifier code, frame size, sample count, and duration for each movie track",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "DR": {
            "ID": "DR",
            "memberOf": "media",
            "identifier": "dataRate",
            "name": "Data Rate",
            "description": "Average movie data rate (kbyte/sec)",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "FF": {
            "ID": "FF",
            "memberOf": "clip",
            "identifier": "format",
            "name": "Format",
            "description": "Summary of media format",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true,
            "isSortable": true
        },
        "FR": {
            "ID": "FR",
            "memberOf": "media",
            "identifier": "frameRate",
            "name": "Frame Rate",
            "description": "Video frame rate",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "FS": {
            "ID": "FS",
            "memberOf": "media",
            "identifier": "frameSize",
            "name": "Frame Size",
            "description": "Video frame size",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "ASP": {
            "ID": "ASP",
            "memberOf": "media",
            "identifier": "aspectRatio",
            "name": "Aspect Ratio",
            "description": "Video playback aspect ratio",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "MPX": {
            "ID": "MPX",
            "memberOf": "media",
            "identifier": "megapixels",
            "name": "Megapixels",
            "description": "Video frame size in megapixels",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "NT2": {
            "ID": "NT2",
            "memberOf": "clip",
            "identifier": "importNotes",
            "name": "Import Notes",
            "description": "Notes or warnings from importing the clip",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "HIS": {
            "ID": "HIS",
            "memberOf": "clip",
            "identifier": "history",
            "name": "Status History",
            "description": "Clip status history",
            "fieldType": "history",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "FLD": {
            "ID": "FLD",
            "memberOf": "media",
            "identifier": "fileDir",
            "name": "Media Folder",
            "description": "Source media file location (full path of parent folder)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "SM": {
            "ID": "SM",
            "memberOf": "media",
            "identifier": "filePath",
            "name": "Source Media",
            "description": "Source media file name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "MD2": {
            "ID": "MD2",
            "memberOf": "media",
            "identifier": "modifiedDate",
            "name": "Media Date",
            "description": "Source media file modification date",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MS": {
            "ID": "MS",
            "memberOf": "media",
            "identifier": "fileSize",
            "name": "Media Size",
            "description": "Source media file size",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MF": {
            "ID": "MF",
            "memberOf": "media",
            "identifier": "filePath",
            "name": "Media Path",
            "description": "Source media file, as a complete path",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "MF2": {
            "ID": "MF2",
            "memberOf": "media",
            "identifier": "filePath",
            "name": "Folder name",
            "description": "Media file parent folder, as a short name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TF": {
            "ID": "TF",
            "memberOf": "clip",
            "identifier": "timebase",
            "name": "Time Base",
            "description": "Timecode format",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "OR": {
            "ID": "OR",
            "memberOf": "clip",
            "identifier": "orientation",
            "name": "Orientation",
            "description": "Image rotation",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "UD": {
            "ID": "UD",
            "memberOf": "media",
            "identifier": "metadata",
            "name": "Metadata (Media)",
            "description": "Concatenated list of QuickTime annotations and other media metadata fields",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "UD2": {
            "ID": "UD2",
            "memberOf": "clip",
            "identifier": "logtext",
            "name": "Metadata (User)",
            "description": "Concatenated list of all user-defined fields",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "ISD": {
            "ID": "ISD",
            "memberOf": "importSource",
            "identifier": "metadata",
            "name": "Metadata (File)",
            "description": "Concatenated list of file metadata fields",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TX": {
            "ID": "TX",
            "memberOf": "clip",
            "identifier": "transition",
            "name": "Transition",
            "description": "Details of transition for clips imported from an EDL",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "SL": {
            "ID": "SL",
            "memberOf": "clip",
            "identifier": "sizeOrLength",
            "name": "Size or Length",
            "description": "Image size (for stills) or length (for movies)",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "NQT": {
            "ID": "NQT",
            "memberOf": "clip",
            "identifier": "nameOrTape",
            "name": "Name or Tape",
            "description": "Name (for stills) or tape & timecode (for movies)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "NL": {
            "ID": "NL",
            "memberOf": "clip",
            "identifier": "nameOrLength",
            "name": "Name or Length",
            "description": "Name (for stills) or length (for movies)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TM": {
            "ID": "TM",
            "memberOf": "clip",
            "identifier": "tapeOrMedia",
            "name": "Tape or Media",
            "description": "Tape or media file name (used as key to look up thumbnails and proxies)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "PF": {
            "ID": "PF",
            "memberOf": "media",
            "identifier": "proxyPath",
            "name": "Proxy File",
            "description": "Name of proxy movie file, if any",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TCH": {
            "ID": "TCH",
            "memberOf": "clip",
            "identifier": "totalCharacters",
            "name": "Total Characters",
            "description": "Total length of comment text, user fields and metadata",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "SIG": {
            "ID": "SIG",
            "memberOf": "media",
            "identifier": "mediaSignature",
            "name": "Media Signature",
            "description": "Unique signature of the clip's media, based on tape, timecode, and/or file name",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "CREF": {
            "ID": "CREF",
            "memberOf": "clip",
            "identifier": "clipref",
            "name": "Clip ID",
            "description": "Optional, user-defined clip id or reference (eg. FCP uuid)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "CAT": {
            "ID": "CAT",
            "memberOf": "catalog",
            "identifier": "name",
            "name": "Catalog",
            "description": "Name of catalog containing clip",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "CNT": {
            "ID": "CNT",
            "memberOf": "catalog",
            "identifier": "comment",
            "name": "Catalog Notes",
            "description": "Catalog comments",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "CUSR": {
            "ID": "CUSR",
            "memberOf": "catalog",
            "identifier": "userID",
            "name": "Catalog Owner",
            "description": "Which user owns the catalog",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "CGRP": {
            "ID": "CGRP",
            "memberOf": "catalog",
            "identifier": "groupID",
            "name": "Catalog Group",
            "description": "Which group owns the catalog",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "OWNER": {
            "ID": "OWNER",
            "memberOf": "clip",
            "identifier": "userName",
            "name": "Clip Owner",
            "description": "Which user created the clip",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "RD2": {
            "ID": "RD2",
            "memberOf": "clip",
            "identifier": "gmtDate",
            "name": "GMT Date",
            "description": "Source date/original record date (corrected for GMT)",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "RD3": {
            "ID": "RD3",
            "memberOf": "clip",
            "identifier": "recordedDate",
            "name": "Location Date",
            "description": "Source date/record date (corrected for shot location)",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TZC": {
            "ID": "TZC",
            "memberOf": "clip",
            "identifier": "clockAdjust",
            "name": "Clock Adjustment",
            "description": "Timezone that the camera clock was set to",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TZL": {
            "ID": "TZL",
            "memberOf": "TZL",
            "identifier": "locationTimezone",
            "name": "Location Timezone",
            "description": "Timezone of the shot location",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TCEVT": {
            "ID": "TCEVT",
            "memberOf": "clip",
            "identifier": "eventMarkerSummary",
            "name": "Event Markers",
            "description": "List of timecode markers within the clip",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "RID": {
            "ID": "RID",
            "memberOf": "clip",
            "identifier": "ID",
            "name": "Remote ID",
            "description": "Unique database id of this clip on the server",
            "fieldType": "other",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "ARCHV": {
            "ID": "ARCHV",
            "memberOf": "media",
            "identifier": "archiveStatus",
            "name": "Archive Details",
            "description": "Has the media been archived to tape?",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "ARCHS": {
            "ID": "ARCHS",
            "memberOf": "media",
            "identifier": "archiveTape",
            "name": "Archive Summary",
            "description": "Has the media been archived to tape?",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "ARCHT": {
            "ID": "ARCHT",
            "memberOf": "media",
            "identifier": "archiveSummary",
            "name": "Archive Tape",
            "description": "Which tape has the media been archived to",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPP": {
            "ID": "TPP",
            "memberOf": "media",
            "identifier": "physicalTape",
            "name": "Physical Tape",
            "description": "Same as Tape field unless tape has timecode breaks, in which case latter defines separate 'virtual' tapes",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": false,
            "isCalculated": true,
            "isEditable": true,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPD": {
            "ID": "TPD",
            "memberOf": "tapeInfo",
            "identifier": "description",
            "name": "Tape Description",
            "description": "Description of the whole tape's contents",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPN": {
            "ID": "TPN",
            "memberOf": "tapeInfo",
            "identifier": "notes",
            "name": "Tape Notes",
            "description": "Notes about the physical tape",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPFMT": {
            "ID": "TPFMT",
            "memberOf": "tapeInfo",
            "identifier": "format",
            "name": "Tape Format",
            "description": "Format of the physical tape",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPLOC": {
            "ID": "TPLOC",
            "memberOf": "tapeInfo",
            "identifier": "location",
            "name": "Tape Location",
            "description": "Shelf location of the physical tape",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "REEL": {
            "ID": "REEL",
            "memberOf": "tapeInfo",
            "identifier": "reelNumber",
            "name": "Barcode",
            "description": "Reel number or barcode number of the physical tape",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPROJ": {
            "ID": "TPROJ",
            "memberOf": "tapeInfo",
            "identifier": "project",
            "name": "Tape Project",
            "description": "Project or department the physical tape relates to",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPSUBJ": {
            "ID": "TPSUBJ",
            "memberOf": "tapeInfo",
            "identifier": "subject",
            "name": "Tape Subject",
            "description": "Tape subject",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPSTAT": {
            "ID": "TPSTAT",
            "memberOf": "tapeInfo",
            "identifier": "status",
            "name": "Tape Status",
            "description": "Tape status (eg. master or not)",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": true
        },
        "TPHIST": {
            "ID": "TPHIST",
            "memberOf": "tapeInfo",
            "identifier": "history",
            "name": "Tape History",
            "description": "Who edited the tape record",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPCREAT": {
            "ID": "TPCREAT",
            "memberOf": "tapeInfo",
            "identifier": "createdDate",
            "name": "Tape Created",
            "description": "When the tape record was created",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPMODF": {
            "ID": "TPMODF",
            "memberOf": "tapeInfo",
            "identifier": "modifiedDate",
            "name": "Tape Modified",
            "description": "When the tape record was last modified",
            "fieldType": "datetime",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        },
        "TPVIDG": {
            "ID": "TPVIDG",
            "memberOf": "tapeInfo",
            "identifier": "videographer",
            "name": "Tape Videographer",
            "description": "Videographer or shooter who originally recorded the tape",
            "fieldType": "text",
            "isBuiltin": true,
            "canQuery": true,
            "isCalculated": false,
            "isEditable": false,
            "isMandatory": false,
            "isMultiValue": false,
            "isList": false
        }
    };
}